ToMyongJi/ToMyongJi-back

tomyongji/build.gradle
tomyongji/src/main/java/com/example/tomyongji/auth/config/EmailConfig.java
tomyongji/src/main/java/com/example/tomyongji/auth/config/ModelMapperConfig.java
tomyongji/src/main/java/com/example/tomyongji/auth/config/SecurityConfig.java
tomyongji/src/main/java/com/example/tomyongji/auth/config/SwaggerConfig.java
tomyongji/src/main/java/com/example/tomyongji/auth/constant/JwtConstant.java
tomyongji/src/main/java/com/example/tomyongji/auth/controller/EmailController.java
tomyongji/src/main/java/com/example/tomyongji/auth/controller/UserController.java
tomyongji/src/main/java/com/example/tomyongji/auth/dto/CustomUserInfoDto.java
tomyongji/src/main/java/com/example/tomyongji/auth/dto/EmailDto.java
tomyongji/src/main/java/com/example/tomyongji/auth/dto/ErrorResponseDto.java
tomyongji/src/main/java/com/example/tomyongji/auth/dto/JwtToken.java
tomyongji/src/main/java/com/example/tomyongji/auth/dto/LoginRequestDto.java
tomyongji/src/main/java/com/example/tomyongji/auth/dto/UserRequsetDto.java
tomyongji/src/main/java/com/example/tomyongji/auth/dto/VerifyDto.java
tomyongji/src/main/java/com/example/tomyongji/auth/entity/EmailVerification.java
tomyongji/src/main/java/com/example/tomyongji/auth/entity/User.java
tomyongji/src/main/java/com/example/tomyongji/auth/jwt/JwtAuthenticationFilter.java
tomyongji/src/main/java/com/example/tomyongji/auth/jwt/JwtDto.java
tomyongji/src/main/java/com/example/tomyongji/auth/jwt/JwtProvider.java
tomyongji/src/main/java/com/example/tomyongji/auth/jwt/JwtToken.java
tomyongji/src/main/java/com/example/tomyongji/auth/repository/EmailVerificationRepository.java
tomyongji/src/main/java/com/example/tomyongji/auth/repository/UserRepository.java
tomyongji/src/main/java/com/example/tomyongji/auth/service/CustomUserDetails.java
tomyongji/src/main/java/com/example/tomyongji/auth/service/CustomUserDetailsService.java
tomyongji/src/main/java/com/example/tomyongji/auth/service/EmailService.java
tomyongji/src/main/java/com/example/tomyongji/auth/service/UserService.java
tomyongji/src/main/java/com/example/tomyongji/auth/service/UserServiceImpl.java
tomyongji/src/main/resources/application.properties

회원가입, 이메일 인증, 로그인 구현

---

tomyongji/src/main/java/com/example/tomyongji/auth/dto/UserRequsetDto.java
tomyongji/src/main/java/com/example/tomyongji/my/dto/MyDto.java
tomyongji/src/main/java/com/example/tomyongji/my/service/MyService.java

회원가입dto, my dto 수정

---

Dockerfile
nginx/conf.d/nginx.conf
src/main/java/com/example/tomyongji/admin/dto/ApiResponse.java
src/main/java/com/example/tomyongji/auth/controller/EmailController.java
src/main/java/com/example/tomyongji/auth/controller/UserController.java

반환값을 response dto를 활용하는 것으로 객체 변경

response 객체 변경

---

docker-compose.yml
nginx/conf.d/nginx.conf
src/main/java/com/example/tomyongji/auth/config/EmailConfig.java
src/main/resources/application.properties

gmail create

---

src/main/java/com/example/tomyongji/TomyongjiApplication.java
src/main/java/com/example/tomyongji/receipt/controller/FindController.java
src/main/java/com/example/tomyongji/receipt/dto/ClubDto.java
src/main/java/com/example/tomyongji/receipt/dto/CollegeDto.java
src/main/java/com/example/tomyongji/receipt/dto/CollegesDto.java
src/main/java/com/example/tomyongji/receipt/entity/College.java
src/main/java/com/example/tomyongji/receipt/entity/StudentClub.java
src/main/java/com/example/tomyongji/receipt/service/CollegeService.java
src/main/java/com/example/tomyongji/receipt/service/OCRService.java
src/main/java/com/example/tomyongji/receipt/service/StudentClubService.java
src/main/resources/application.properties

진형님 코드 수정: 모든 대학조회

---

src/main/java/com/example/tomyongji/admin/service/AdminService.java
src/main/java/com/example/tomyongji/receipt/entity/Receipt.java
src/main/java/com/example/tomyongji/receipt/mapper/StudentClubMapper.java
src/main/java/com/example/tomyongji/receipt/repository/StudentClubRepository.java
src/main/java/com/example/tomyongji/receipt/service/CollegeService.java

entity 잔액 칼럼 추가

---

src/main/java/com/example/tomyongji/admin/service/AdminService.java
src/main/java/com/example/tomyongji/auth/entity/User.java
src/main/java/com/example/tomyongji/my/mapper/MyMapper.java
src/main/java/com/example/tomyongji/my/service/MyService.java
src/main/java/com/example/tomyongji/receipt/repository/StudentClubRepository.java
src/main/java/com/example/tomyongji/receipt/service/CollegeService.java

-AdminSerive/getMembers()
-CollegeService/getAllCollegesAndClubs()
위 두 메서드에 대한 오류 수정

erd 수정 후 메서드 오류 수정

---

src/main/java/com/example/tomyongji/receipt/entity/Receipt.java
src/main/java/com/example/tomyongji/receipt/entity/StudentClub.java

receipt에 잔액 칼럼을 넣기로 했던것을 
데이터 무결성 및 용량 낭비를 방지하기 위해 
각 학생회 studentClub entity 테이블에 잔액 칼럼을 추가하는것으로 변경하였습니다.

receipt> balance => studentclub > balance 변경

---

src/main/java/com/example/tomyongji/auth/controller/UserController.java
src/main/java/com/example/tomyongji/auth/entity/ClubVerification.java
src/main/java/com/example/tomyongji/auth/repository/ClubVerificationRepository.java
src/main/java/com/example/tomyongji/auth/repository/EmailVerificationRepository.java
src/main/java/com/example/tomyongji/auth/repository/UserRepository.java
src/main/java/com/example/tomyongji/auth/service/EmailService.java
src/main/java/com/example/tomyongji/auth/service/UserService.java
src/main/java/com/example/tomyongji/auth/service/UserServiceImpl.java
src/main/java/com/example/tomyongji/receipt/entity/College.java
src/main/java/com/example/tomyongji/receipt/repository/CollegeRepository.java
src/main/java/com/example/tomyongji/receipt/repository/StudentClubRepository.java
src/main/java/com/example/tomyongji/validation/ErrorMsg.java
src/test/java/com/example/tomyongji/UserServiceTest.java

> #103 
> SignUp부분에서 부족한 exception처리
> repository 함수 return 값 통일- Optional

Refactor : 코드 개발 규칙에 맞게 기능 코드 수정

---

src/main/java/com/example/tomyongji/auth/controller/UserController.java
src/main/java/com/example/tomyongji/auth/repository/EmailVerificationRepository.java
src/main/java/com/example/tomyongji/auth/service/UserService.java
src/main/java/com/example/tomyongji/auth/service/UserServiceImpl.java
src/test/java/com/example/tomyongji/UserTest.java
src/test/java/resources/application.properties

Related #100 
User 통합테스트 signup, id 중복검사 개발

Test: User 통합테스트

---

src/main/java/com/example/tomyongji/auth/dto/EmailDto.java
src/test/java/com/example/tomyongji/UserTest.java

> Resolves #100
> Email 통합테스트 마무리

Test: Email 통합테스트

---

src/main/java/com/example/tomyongji/admin/controller/AdminController.java
src/main/java/com/example/tomyongji/admin/dto/PresidentDto.java
src/main/java/com/example/tomyongji/admin/service/AdminService.java
src/main/java/com/example/tomyongji/my/dto/AdminSaveMemberDto.java
src/test/java/com/example/tomyongji/AdminServiceTest.java

> Resolves #110
>  AdminService  유닛테스트 마무리
> ![스크린샷 2025-01-08 172233](https://github.com/user-attachments/assets/ec412e19-8673-4c9c-9b00-751918371e21)

Test: AdminService 유닛테스트

---

src/main/java/com/example/tomyongji/auth/entity/EmailVerification.java

회원가입 오류 해결 - emailVerification generated id

회원가입 오류 해결

---

src/main/java/com/example/tomyongji/receipt/controller/ReceiptController.java
src/test/java/com/example/tomyongji/MyTest.java
src/test/java/com/example/tomyongji/ReceiptTest.java

#122 
Receipt 생성, 조회, 수정, 삭제 흐름 테스트코드 작성
College 전체 조회 흐름 테스트코드 작성
StudentClub 전체 및 단과대별 조회 흐름 테스트코드 작성

Receipt 패키지 통합 테스트 코드 개발

---

src/main/java/com/example/tomyongji/auth/repository/ClubVerificationRepository.java
src/main/java/com/example/tomyongji/auth/repository/EmailVerificationRepository.java
src/main/java/com/example/tomyongji/auth/service/EmailService.java
src/main/java/com/example/tomyongji/auth/service/UserServiceImpl.java
src/test/java/com/example/tomyongji/UserTest.java

> 이슈 존재하지 않음
> 회원가입 및 소속, 이메일 인증시 여러번 인증한 경우 발생하는 오류 해결
> ![image](https://github.com/user-attachments/assets/c2e6bdb3-1d05-4f65-8421-e74565ae54af)

Fix: 회원가입 및 소속,이메일 인증시 중복 오류 해결

---

src/main/java/com/example/tomyongji/admin/service/AdminService.java

AdminService의 deleteMember에 @Transactional 추가
user 삭제 시 clubVerification부터 삭제하는 로직으로 변경
@RequiredArgsConstructor를 통해 생성자를 지워 가독성 향상

Refactor : AdminService 부원 삭제 수정

---

src/main/java/com/example/tomyongji/auth/config/SecurityConfig.java
src/main/java/com/example/tomyongji/auth/controller/UserController.java
src/main/java/com/example/tomyongji/auth/dto/ClubVerifyRequestDto.java
src/main/java/com/example/tomyongji/auth/service/UserService.java
src/main/java/com/example/tomyongji/auth/service/UserServiceImpl.java
src/main/java/com/example/tomyongji/validation/ErrorMsg.java
src/test/java/com/example/tomyongji/UserServiceTest.java
src/test/java/com/example/tomyongji/UserTest.java

> not
> Security Config 파일에 각 경로에 대한 인가 코드 추가 (주석)
> 소속인증 API request 수정 (pathvariable -> Body)
> 소속인증 http Method 수정 (GET-> POST)
> 소속인증 각 역할에 따른 소속인증 로직 수정
> 
>

Chore : 소속인증 api 수정

---

src/main/java/com/example/tomyongji/admin/repository/PresidentRepository.java
src/main/java/com/example/tomyongji/auth/config/SecurityConfig.java
src/main/java/com/example/tomyongji/auth/service/UserServiceImpl.java
src/test/java/com/example/tomyongji/AdminTest.java
src/test/java/com/example/tomyongji/UserServiceTest.java
src/test/java/com/example/tomyongji/UserTest.java

> related #112 
> TestCode 토큰 코드 추가
> ![image](https://github.com/user-attachments/assets/f8dd8a50-fc18-4f19-ad41-18fe530604dd)
>

Test: TestCode 수정: 토큰 코드 추가

---

src/main/java/com/example/tomyongji/auth/service/UserServiceImpl.java

> #129 
> 해당 email의 계정이 여러개인경우 버그 발생
signup -> email 중복검사추가
> 
>

Fix : find-id 버그 수정

---

src/main/java/com/example/tomyongji/receipt/service/CSVService.java

Fix : csv 잔액 부분 수정

---

src/main/java/com/example/tomyongji/auth/service/UserServiceImpl.java

> resolved #133
> 소속인증의 소속과 학생을 비교하여 체크하는 부분을 추가
>
>

Fix : 소속인증 부분 버그 수정

---

src/main/java/com/example/tomyongji/receipt/controller/OCRController.java
src/main/java/com/example/tomyongji/receipt/service/OCRService.java
src/main/resources/application.properties

#140 
OCR 이미지 용량을 위해 application.properties 수정 및 업로드 서비스단 로직 수정

Refactor : OCR 로직 수정

---

build.gradle
src/main/java/com/example/tomyongji/auth/service/UserServiceImpl.java
src/test/java/com/example/tomyongji/MyTest.java

> #142 
> Jacoco Test 분석 툴 설정
> ![image](https://github.com/user-attachments/assets/424a84d2-6aa0-4e9e-8fe8-a628d383f92f)
>

Test : Jacoco 설정

---

src/main/java/com/example/tomyongji/auth/config/SecurityConfig.java
src/test/java/com/example/tomyongji/AdminTest.java
src/test/java/com/example/tomyongji/UserServiceTest.java

> #142
> UserService와 Admin Test Class에 대해 오류를 수정했습니다.
> 
>

Test : UserService, Admin Test 오류 수정

---

build.gradle
docker-compose.yml
loki-config.yml
promtail-config.yml
src/main/java/com/example/tomyongji/TomyongjiApplication.java
src/main/java/com/example/tomyongji/config/EmailConfig.java
src/main/java/com/example/tomyongji/config/ModelMapperConfig.java
src/main/java/com/example/tomyongji/config/RequestLoggingConfig.java
src/main/java/com/example/tomyongji/config/SecurityConfig.java
src/main/java/com/example/tomyongji/config/SwaggerConfig.java
src/main/resources/application.properties
src/main/resources/logback-spring.xml
var/log/tomyongji/console.log

>resolved #147
> INFO 수준으로 로그가 찍히도록 했습니다.
> ![image](https://github.com/user-attachments/assets/d0cd89cd-498d-4541-9376-b33f8717932b)
>

Feat : Log 기능 추가

---

docker-compose.yml
loki-config.yml
promtail-config.yml
var/log/tomyongji/mainLog.2025-03-21_0.log
var/log/tomyongji/mainLog.log

> 
> docker-compose.yml, prometheus.yml, promtail.yml,loki-config.yml 수정
> 테스트 결과나 스크린 샷으로 보여줘야하는 부분을 삽입해주세요,
> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
>
> ex) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

Feat: 모니터링, 로깅 구현

---

src/main/java/com/example/tomyongji/auth/entity/User.java
src/main/java/com/example/tomyongji/auth/service/UserServiceImpl.java
src/main/java/com/example/tomyongji/validation/GlobalExceptionHandler.java

#161 
User 엔티티의 userId에 @Column(unique = true) 추가
signUp()에 @Transactional 추가
GlobalExceptionHandler에 DB관련 처리 추가

Refactor: 중복 로그인 해결

---

src/main/java/com/example/tomyongji/receipt/controller/BreakDownController.java
src/main/java/com/example/tomyongji/receipt/dto/BreakDownDto.java
src/main/java/com/example/tomyongji/receipt/mapper/ReceiptMapper.java
src/main/java/com/example/tomyongji/receipt/repository/ReceiptRepository.java
src/main/java/com/example/tomyongji/receipt/repository/StudentClubRepository.java
src/main/java/com/example/tomyongji/receipt/service/BreakDownService.java

> #178 
> PDF 파싱 메서드 변경
변경 전 : 내부 로직으로 검증 번호를 받아 직접 진위 여부 확인 후 승인 
변경 후 : 내부 로직이 아닌 토스뱅크로 직접 보낸 후 받은 응답으로 여부 확인 후 승인

토스뱅크 거래내역서 기반 업로드 (자동화)

---

config/prod/docker-compose.yml

Refactor : docker-compose.yml 오타 수정

---

config/prod/docker-compose.yml

Refactor : docker-compose.yml 보완

---

config/prod/docker-compose.yml

Refactor : docker-compose.yml 수정

---

config/prod/app.Dockerfile

Refactor : prod/app.Dockerfile 수정

---

src/main/java/com/example/tomyongji/admin/controller/AdminController.java
src/main/java/com/example/tomyongji/auth/service/CustomUserDetails.java
src/main/java/com/example/tomyongji/my/controller/MyController.java
src/main/java/com/example/tomyongji/receipt/controller/BreakDownController.java
src/main/java/com/example/tomyongji/receipt/controller/CsvController.java
src/main/java/com/example/tomyongji/receipt/controller/OCRController.java
src/main/java/com/example/tomyongji/receipt/controller/ReceiptController.java
src/main/java/com/example/tomyongji/receipt/controller/StudentClubController.java
src/main/java/com/example/tomyongji/receipt/entity/StudentClub.java
src/main/java/com/example/tomyongji/receipt/service/CSVService.java
src/main/java/com/example/tomyongji/receipt/service/CollegeService.java
src/main/java/com/example/tomyongji/receipt/service/OCRService.java
src/main/java/com/example/tomyongji/receipt/service/ReceiptService.java
src/main/java/com/example/tomyongji/receipt/service/StudentClubService.java
src/test/java/com/example/tomyongji/CSVTest.java
src/test/java/com/example/tomyongji/OCRTest.java

>  #247 
> 테스트 코드에서 빠진 실패 케이스들 추가
-OCR은 통합 테스트 코드가 없어 개발
-CSV 실패 케이스 추가 (커밋 확인)
-BreakDown 테스트 코드는 실패 케이스 테스트 코드가 작성되어 있어 추가 작성 X
> CSV 코드
>OCR 코드

Refactor : 테스트 코드 실패 케이스 추가
